### ISSUE TITLE
Searches containing only stopwords are not being handled correctly

### ISSUE THREAD

**Issue by chalkos** [keeps/db-visualization-toolkit#117]
The issue can be reproduced in database "World".
1. Open visualisation toolkit -> database "World"
2. Click "Data" -> "Country"
3. Click the arrow near the search button then the form opens where you can see the fields.
4. Insert "Estonia" as the "Name" and click "Search"
You will be displayed 1 result.
5. Insert "Are" (or any other stopword) as the "Name" and click "Search"
You will be displayed 239 results (all of them).

Expected behaviour: Searches containing only stopwords should not return any results.

**Comment by chalkos** [comment]
Related to #116, reported by @laurira

**Comment by luis100** [comment]
This is mitigated by #125
