### ISSUE TITLE
Improve search completeness and accuracy 

### ISSUE THREAD

**Issue by chalkos** [keeps/db-visualization-toolkit#119]
When a search query contains stopwords they are ignored, but this might not be the expected behaviour from the users point of view (as he might be expecting some more results than the ones shown).

Solution:
- Start by showing records that match the search without stopwords;
- Show records matching any part of the search query.

This way all the expected search results are there, but the ones that the user is most likely looking for are displayed first.

Internally, this would require records to be indexed with and without stopwords, and modifying the ranking of matches on the "considering stopwords" search field to be much higher (so those results always appear first).

Idea source & more info: https://stackoverflow.com/a/31850227

**Comment by chalkos** [comment]
Related to #116, reported by @Laurira

**Comment by luis100** [comment]
This is mitigated by #125
