### ISSUE TITLE
Re-organize sidebar content

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#127]
Prioritize the sidebar, separate “technical information” and “content information”
User A - advanced user (interested in everything)
User B - novel end user (interested in the metadata)

- **Information** (but only with “content information): 
  -  Database name 
  -  Data origin time span
  -  Data creator/owner 
  -  Description
- **Search all records** (Because this is probably the second need for an end user)
- **Saved searches**
- **Report** (What is this? Last or hide from end user because it is rarely used by an end user)
- **Users & Roles** (Last or hide because it is rarely used by an end user) Or at least the user should be explained what this information can be used for.
- **Technical** (or internal) information (displaying this information:
  -  Archival date
  -  Archivist
  -  Archivist contact
  -  Client machine
  -  Database product
  -  Producer application)

**Comment by luis100** [comment]
Routines, Triggers and Check constraints, Views pages contain information not relevant for end user

This information is very technical. End user gets confused and waste time trying to understand information he doesn’t need. 
If relevant for other users, then clarify that this is only technical information for special users. 
Or somehow hide it away under “Technical  information” for specialists/IT-user

**Comment by Laurira** [comment]
"Archival date" should not be in technical section.

**Comment by hmiguim** [comment]
Closed at ec16ab8
