### ISSUE TITLE
Improve and allow export of a single row

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#134]
User needs readable reports as export of data of single rows in a result. Make readable reports before export of data. This is an export often made by the archivist to the end user and it is very time consuming to do manually, eg. Edit the data in excel when the export has 20 or more columns 

Make a standard report for export of data in the case, where only a single row in a search result is to be exported to the end user.

The report should have a layout that is easier to read and give a better overview of the result than the raw .csv or excel export that is more suitable for export of much data in tabular form.

Problem: DBVTK does not export the original column name. The original column name is essential for the end user to understand the data export. #65 

Problem: Column descriptions are also very useful in an export. So think carefully how this can be presented for the user in the report of data

**Comment by hmiguim** [comment]
Add a button on the record page to export the row.

**Comment by hmiguim** [comment]
Close at 3250f26
