### ISSUE TITLE
Startup script to dynamically allocate memory by default

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#135]
Problem: Bigger databases could not be loaded, memory issue. We had to add "solr/bin/solr start -c -m 8G -force" to the bat file. DBVTK should be taken memory more dynamically.

Change the start script to support dynamic allocation of memory up to maximum value.
Allow to statically set the memory maximum with an environment variable and/or a configuration.

**Comment by 006627** [comment]
Closed at keeps/db-visualization-toolkit-electron@c4f658f
