### ISSUE TITLE
Column descriptions on export

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#141]
Add table and column descriptions to the export of data as well when user checks this option.

After export there should be asked if user should add the metadata (descriptions) as well. Also the "Export visible" option should be here.

**Comment by hmiguim** [comment]
Close at f19c75c

**Comment by Laurira** [comment]
It works but the formatting of linebreaks are not very intuitive:
![image](https://user-images.githubusercontent.com/3479156/70036284-1e534f80-15bd-11ea-9789-424513d56dd0.png)
or
![image](https://user-images.githubusercontent.com/3479156/70036299-28754e00-15bd-11ea-9205-ea8c65e7cdca.png)

Maybe the line break should be replaced with ": ", then it should be something like this:
![image](https://user-images.githubusercontent.com/3479156/70036393-61adbe00-15bd-11ea-94f7-234f17413237.png)
