### ISSUE TITLE
Hint for advanced search (usability)

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#142]
Search in single table: User can’t find ‘Advanced search’ for a single table 

User B quickly needed to make an advanced search into specific columns in a single table. But he could not find the advanced search. 
An Advanced Search suddenly appeared for a table, when he clicked a reference to another table. User B didn’t remember what he did to make this Advanced Search appear again.
The little arrow on the right of the simple search field can be used to expand the Advanced Search. But it should be more explicit how to do this. E.g. by renaming the arrow to “Advanced search” or by adding a button under the search field called “Advanced search”.

**Comment by hmiguim** [comment]
Close at f4da936
