### ISSUE TITLE
Support for materialized views

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#145]
Support for presenting and searching on materialized views, as supported in https://github.com/keeps/db-preservation-toolkit/issues/348

**Comment by luis100** [comment]
Since v1.0.7, materialized views are presented as tables with a `VIEW_` prefix but disconnected from the Views definition. Connection to happen in v1.1.0

**Comment by hmiguim** [comment]
Closed at 456bcd0
