### ISSUE TITLE
Improve navigation through references/foreign keys (usability)

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#147]
User gets confused when navigating through references/foreign keys in DBVTK

Guide the user better through the references between tables. Today database logic and concepts are used in DBVTK to guide the user. But the novel end user doesn’t understand this and the advanced user will hardly ever use this functionality in DBVTK.

Rename the foreign keys from sakila.film_category to something the user understands. 
Maybe it would direct the user more if it was called: ‘Go to table X’ or ‘see explanation of code’ .
Answer this question for the user: Where is the user expected to go, when clicking a foreign key? Today they don’t expect anything! They don’t know what the link sakila.film_category is and what happens when they click on it. So when they do, they are very confused because they don’t realize what just happened, where they ended, why this happened and what they are looking at.

Ask a user where he expects to go when clicking a reference and use his answer as a guidance.
This is a creative and iterative process, it depends on the available users to figure out a solution for the usability problem.

**Comment by hmiguim** [comment]
Closed at e3bc60cdeed3e17639ae875ace5762311a9d379d
