### ISSUE TITLE
Search logging

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#148]
It would be important from the security perspective if you can prove who searched some specific keyword.

DBVTK doesn't currently have an authentication system. This requirement entails the initial development of this feature. The task also includes saving searches on a log file, indexing them and displaying a searchable list of query terms for the user to consult.

- [ ]  Integration with authentication system
- [ ]  Log search event into file
- [ ]  Display and search logging on interface

**Comment by hmiguim** [comment]
Close at b3198d4
