### ISSUE TITLE
GWT methods to call Electron API

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#157]
This will possibly need to use [IPC renderer API](https://electronjs.org/docs/api/ipc-renderer)

**Comment by luis100** [comment]
In GWT this will possibly need [JSNI](http://www.gwtproject.org/doc/latest/DevGuideCodingBasicsJSNI.html).

**Comment by luis100** [comment]
Methods needed will include: ([based on Electron API Demos](https://github.com/electron/electron-api-demos/releases))

- [ ] Open Path in File Manager
- [ ] Basic notification
- [ ] Open a File or Directory
- [ ] Drag and drop files
- [ ] Save Dialog

**Comment by 006627** [comment]
closed this in  8d8db29e46cda132a40f5ff8ca352a4321bd1c09 and e94e98d40b79bac1ca4d44d569185cc250d34fc9
