### ISSUE TITLE
Update Solr Collection to have SIARD location information

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#158]
A database can now exist just with SIARD location or with browse collection.

SIARD location needs to be persisted in model. For example in a JSON configuration in home (one per SIARD within a folder). This JSON can later have information about here is the ingest report, when it was last validated and where is the validation report(s).

**Comment by 006627** [comment]
closed this in fc208cc59aba93a6ca2012a0ea191cabd8dc2d54
