### ISSUE TITLE
Interface to show a SIARD

### ISSUE THREAD

**Issue by luis100** [keeps/db-visualization-toolkit#159]
It should use the SIARD itself to get information from metadata and present it in the browser.

Note that classes to be serialized to GWT client need to [follow specific rules](http://www.gwtproject.org/doc/latest/DevGuideServerCommunication.html#DevGuideSerializableTypes).

**Comment by 006627** [comment]
closed this in 9fd7abc1ecf294e1cb5587b9c7d8ea26c7111e7a and 74a3ea6fa4d5788d17cc756d4392c43be8c103c6
