### ISSUE TITLE
centos gnome postgresql: create siard for 15MB database keeps thinking forever

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#163]
The creation process after entering database connection parameters keeps thinking forever (I waited about 10 minutes for 15 MB sized database)

See the video

[keepsThinking.zip](https://github.com/keeps/db-visualization-toolkit/files/3484989/keepsThinking.zip)

Also there are "Next" button always visible and clickable
If I go "Back" then password field is emptied for some reason?

**Comment by Laurira** [comment]
added more logs here

[arendus DBPTK.zip](https://github.com/keeps/db-visualization-toolkit/files/3496025/arendus.DBPTK.zip)

**Comment by Laurira** [comment]
found out with Miguel that the issue is with array datatype

**Comment by hmiguim** [comment]
Closed at e887104
