### ISSUE TITLE
create siard - select table and columns shows no views

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#164]
1. Migrated Sakila from mysql to postgresql
Problem: shows views under the tables, is it normal?
2. Started creating Sakila from postgresql
Problem: shows no views at all
![mysqlPostgres](https://user-images.githubusercontent.com/3479156/63079967-80257600-bf48-11e9-8765-f3a119638bac.JPG)

**Comment by hmiguim** [comment]
Fixed, next release will have the patch.
