### ISSUE TITLE
create siard from mysql: "Please select at least one table or view!"

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#165]
Most of my tables are selected but I get error "Please select at least one table or view".
![Please select at least one table or view](https://user-images.githubusercontent.com/3479156/63080147-0b9f0700-bf49-11e9-916d-0619cd0b9378.JPG)

**Comment by Laurira** [comment]
I tried also selecting all tables and fields but still the same error.

**Comment by hmiguim** [comment]
I found a way to replicate the bug, it is already fixed

**Comment by hmiguim** [comment]
Closed at f0e57c6
