### ISSUE TITLE
Ingest -> open -> all siard file inputs do not get any feedback at all

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#169]
**Home page -> Ingest -> Open**
![ingest](https://user-images.githubusercontent.com/3479156/64231653-e58dd680-cef8-11e9-81d0-603499c401f6.JPG)

**I select file from the list**
![select-file-ingest](https://user-images.githubusercontent.com/3479156/64231758-25ed5480-cef9-11e9-88b4-8ebfda4def23.JPG)

**About 50% of my siard files will not get any feedback when selected**
The blue bubble appears for a second but then nothing....
It should produce error when there are problems with opening siard files.

**Comment by 006627** [comment]
@Laurira could you send me one of the failed SIARD files. (email: gbarros@keep.pt)

**Comment by hmiguim** [comment]
Closed at e887104
