### ISSUE TITLE
Version 2.1

### ISSUE THREAD

**Issue by whsmith100** [keeps/db-visualization-toolkit#171]
Description: 
Is Version 2.1 db-visualization-toolkit compatible with preservation tool kit 2.3 or higher

Browser (Internet explorer, Chrome, Firefox, etc):

Browser version:

Steps required to reproduce the bug:

1. 
2. 
3. 

Attach any related screenshots below.

**Comment by luis100** [comment]
The dbvtk is no longer depending on an external dbptk to ingest databases. Instead, you directly submit the siard file via the web app or the REST API. internally it uses dbptk library version 2.6. Any siard version is supported.
