### ISSUE TITLE
GUI and Command-Line-DBPTK create different siards with default parameters?

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#175]
1. Created sakilaGUI.siard from mysql database "sakila" with GUI with default parameters
![sakilaGUI](https://user-images.githubusercontent.com/3479156/68370471-3f06c180-0145-11ea-98fd-b050dfa5f2ba.JPG)
![sakilaGUI2](https://user-images.githubusercontent.com/3479156/68370472-3f06c180-0145-11ea-9238-b02ef8f198bc.JPG)

2. Created sakila.siard with the latest dbptk (2.6.3) with command line:
![sakilaCOMMAND](https://user-images.githubusercontent.com/3479156/68370506-547beb80-0145-11ea-9a85-5ee21c6f038f.JPG)

3. The sizes of both siard files were different: sakilaGUI.siard 11 MB vs sakila.siard 7MB.
I unpacked it just in case to check if one of these were compressed maybe but the difference remained...
![comparison](https://user-images.githubusercontent.com/3479156/68370601-8c832e80-0145-11ea-9d00-2c7e69c1289c.JPG)

Both siard file are here 
[bothSiardFiles.zip](https://github.com/keeps/db-visualization-toolkit/files/3818467/bothSiardFiles.zip)

**Comment by Laurira** [comment]
Maybe the GUI makes better formatted xml and xsd files... But why don't the command line tool acts differently?

**Comment by hmiguim** [comment]
It was defined and agreed that the GUI will export the SIARD with the pretty-xml option, we could put back on the option for the user to opt out.

**Comment by hmiguim** [comment]
We will add back the pretty-xml option and set the default as the DBPTK

**Comment by hmiguim** [comment]
Close at 2a14b2a
