### ISSUE TITLE
Create SIARDDK - browsing files: fileextension is locked to .siard

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-visualization-toolkit#177]
When I use DBVTK 1.1.1 and pick SIARDDK in CREATE siard function, and then try to browse for some xml-files the pop-up only let me pick .siard-files.
It must be possible to pick any file.

![image](https://user-images.githubusercontent.com/15984159/68585928-d2acfa80-0483-11ea-8297-502152327919.png)

**Comment by hmiguim** [comment]
Close at 6279032
