### ISSUE TITLE
Logo doesn't work well on dark desktops

### ISSUE THREAD

**Issue by jmaferreira** [keeps/db-visualization-toolkit#179]
May add a background color to the logo like the iOS apps.

<img width="504" alt="Screenshot 2019-11-14 at 00 37 52" src="https://user-images.githubusercontent.com/3181302/68810656-64c92480-0677-11ea-9032-af457ba8f14f.png">

**Comment by Laurira** [comment]
This is not exactly a logo but also related to graphical side:

![image](https://user-images.githubusercontent.com/3479156/69714111-7ea24700-110e-11ea-8cee-5c56059ebbf4.png)

**Comment by hmiguim** [comment]
Closed
