### ISSUE TITLE
create siard - "validate" checkbox not starting the process - win10

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#181]
![image](https://user-images.githubusercontent.com/3479156/69800006-0eaec200-11dd-11ea-9da9-f25bb090fbcf.png)

**Comment by hmiguim** [comment]
We will remove this option from the form, since it is causing some confusing. That is an old option that exists in the DBPTK that validates the XML against the XSD. However the DBPTK offers a more complete validation option and that should be used to validate the SIARD file.
