### ISSUE TITLE
description shows "null" when table comment is empty

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#185]
![image](https://user-images.githubusercontent.com/3479156/70990154-9a758900-20cd-11ea-9bc6-fbe1963be32f.png)

**Comment by hmiguim** [comment]
Could you please show me the description for those table in metadata.xml file?

**Comment by Laurira** [comment]
![image](https://user-images.githubusercontent.com/3479156/70994471-fd1f5280-20d6-11ea-9646-c413e1250580.png)

**Comment by Laurira** [comment]
![image](https://user-images.githubusercontent.com/3479156/70994524-1fb16b80-20d7-11ea-8a98-3d93292d0a8e.png)

**Comment by hmiguim** [comment]
The problem resides in the SIARD creation. I'll run some tests and fix the issue.
