### ISSUE TITLE
Version number in settings

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-visualization-toolkit#188]
Is it an idea to have version number in settings?
I was unsure if I had the latest version and had to turn to the list of apps on my PC.
- Best Phillip

**Comment by hmiguim** [comment]
Thanks for the suggestion @PhillipTommerholt. 

On DBPTK Desktop will be added two menu items under 'Help' menu. One to redirect the user for the Changelog and another with the version number. 

Reference: https://github.com/keeps/db-visualization-toolkit-electron/commit/5fc0b0e76a73902ea9a5cc0240c6884e8b813f6f
