### ISSUE TITLE
Load siard files

### ISSUE THREAD

**Issue by domenicoruggeri** [keeps/db-visualization-toolkit#199]
Description: 
Hi,

I am trying the web viewer (tag version 1.0.6 - as it is the only one for which the build works for me) by building the war and deploying the dbvtk-viewer app on a local instance of tomcat. 
I made sure a local instance of solr was running - used a docker container with a solr image. 
Although, when trying to load the siard file, I get prompted with this page:

![image](https://user-images.githubusercontent.com/40301221/77530458-470f9580-6e89-11ea-8124-f5989dfa91e9.png)

By inspecting the web page while hitting ("load siard file"), I have not noticed any request sent to retrieve the file at the specified path, so I don't know exactly what the error is due to.

Thanks a lot in advance for your help,
Dom

Browser (Internet explorer, Chrome, Firefox, etc): Chrome

Browser version:

Steps required to reproduce the bug:

1. Clone and build the war file
2. Deploy to a local instance of tomcat 
3. Input the path and click "load siard file"

Attach any related screenshots below.

**Comment by luis100** [comment]
Can you send the log files?

**Comment by domenicoruggeri** [comment]
The viewer doesn't contain any logs, and the tomcat logs do not show anything. Just the successful deployment I am afraid.

I have tried to setup the debug in super dev mode on intellij, but the gwt debug configuration doesn't allow to select the module and keeping ticked the "super dev mode" at the same time. That is, once I select the module, the option to tick the "super dev mode" box disappears. 
I am not familiar with gwt application and I thought that adding the following two lines to the dbvtkviewer.gwt.xml would do the job, but it doesn't:

<add-linker name="xsiFrame"/>
    <set-configuration-property name="devModeRedirectEnabled" value="true"/>

You think that is the right way to proceed?

**Comment by luis100** [comment]
Logs should be created at ~/.dbvtk/log

In terms of debugging GWT, we are lacking documentation that we will promptly update, but it is done by running in two different terminals the following commands:

```bash
mvn spring-boot:run -Pdebug-server
mvn gwt:codeserver -Pdebug-server
```
Then accessing both services that are displayed in the above command execution output.
You can use intellij but don't need to use gwt plugin, I personally use [VScode](https://code.visualstudio.com/).

But, anyway, I would recommend using the latest version and deploying [Apereo CAS](https://apereo.github.io/cas) alongside the other apps.

We will be deploying a demo site soon, if that would be easier for your evaluation please contact us.

**Comment by domenicoruggeri** [comment]
Thanks for your reply and information.

Unfortunately, my dbvtk folder within tomcat doesn't contain logs.

I tried to run those two commands from the command line and got this output:
![image](https://user-images.githubusercontent.com/40301221/77556216-1e4ec680-6eb0-11ea-85f9-a08ac05c29ee.png)

![image](https://user-images.githubusercontent.com/40301221/77556165-0a0ac980-6eb0-11ea-8715-3d9150e596a2.png)

It looks like the pom does not contain any of those profiles. Would you suggest to copy them - haven't check if they have them yet - from the more recent versions' pom?

I have tried to clone the master branch. It built fine, but the deployment keeps failing. I had a problem with a missing jar (orai18n-mapping.jar) that I have added to the WEB-INF/lib, but now it throws a different error (logs attached below). The application's name is **dbvtk-master**
[catalina.2020-03-26.log](https://github.com/keeps/db-visualization-toolkit/files/4386974/catalina.2020-03-26.log)

I am sorry you need to deal with comments on two versions at the same time, but I thought it was worth adding both so that you could recommend the best way to proceed (i.e. which version is more likely to work).

Many thanks,
Dom

P.S.: In my first comment I haven't added the following console's error on Chrome, but I am not sure if that would help: 
![image](https://user-images.githubusercontent.com/40301221/77555961-c31cd400-6eaf-11ea-8134-037d188c8aff.png)

**Comment by luis100** [comment]
The commands only work in latest versions.
The war file is not supposed to be deployed in a tomcat, it must use spring boot that is embed into the war file, and spring boot uses embed tomcat. Just java -jar the war file to fire up the tool.

I'm still working on putting up Apereo CAS on the demo site, but could not get the time to do it yet. Will update this issue when it is done.

**Comment by hmiguim** [comment]
Closed at https://github.com/keeps/db-visualization-toolkit-docker/issues/7

**Comment by domenicoruggeri** [comment]
Hi,

Sorry I could not go back to this earlier.

I have tested it by cloning the repo, building the jar as suggested and deploying it; and so far so good. Although, once I browse to localhost:8080/#home and I am still prompted with this page 
![image](https://user-images.githubusercontent.com/40301221/80090064-d70f3080-8556-11ea-8843-5548eb35e1d3.png)

and clicking "Login" results in an error page. This is the network log:
![image](https://user-images.githubusercontent.com/40301221/80089399-c611ef80-8555-11ea-9e82-8429d43ba556.png).
Are the Apereo CAS in for this project too? Or maybe I am going to the wrong url and there is a way of skipping the login step?

**Comment by luis100** [comment]
New version that was released does not require Apereo CAS, you can set `CAS_ENABLED=false`.

**Comment by domenicoruggeri** [comment]
Thanks a lot for the help Luis. That solved it!
