### ISSUE TITLE
Triggering Docker project build with travis script don't work with tags

### ISSUE THREAD

**Issue by 006627** [keeps/db-visualization-toolkit#206]
Description: 
When building a tag, the [script](https://github.com/keeps/db-visualization-toolkit/blob/master/.travis/trigger-travis-build.sh) makes a request to [dbvtk-docker](https://github.com/keeps/db-visualization-toolkit-docker) repository in order to generate a image in dockerhub, but the request is refused because the script is send the tag as a branch

**Comment by hmiguim** [comment]
Close at b36af97
