### ISSUE TITLE
Can't open .siard-file after creating it in 2.4.0

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-visualization-toolkit#208]
Description: 
Can't open/import .siard-file after creating it in 2.4.0 Windows Desktop Version
Steps required to reproduce the bug:

1. I created a .siard-file in create-mode
2. After successful creation I get a pop-up asking if I want to import. I click Yes.
3. I get the attached error. Which I also get when trying to open manually

Attach any related screenshots below.
Error:
![image](https://user-images.githubusercontent.com/15984159/79550636-ebf04d80-8098-11ea-830c-0a4a8783dd55.png)
The file does exist:
![image](https://user-images.githubusercontent.com/15984159/79550959-543f2f00-8099-11ea-80bb-96483c18b41f.png)
The file (i just added .zip in filename, so that I was able to upload here):

[Northwind_17_4 - Kopi.siard.zip](https://github.com/keeps/db-visualization-toolkit/files/4491897/Northwind_17_4.-.Kopi.siard.zip)

**Comment by PhillipTommerholt** [comment]
It is the Windows Desktop version.

**Comment by hmiguim** [comment]
@PhillipTommerholt by mistake I left a property pointing to my local machine. 

It is fixed, that property is now being ignored when in desktop environment.
