### ISSUE TITLE
Missing customized views

### ISSUE THREAD

**Issue by hmiguim** [keeps/db-visualization-toolkit#211]
From https://github.com/keeps/db-preservation-toolkit/issues/446:
> We are trying to cerate custom views for the first time and have defined, tested and saved 3 views before creating SIARD-file. When creation process is done, only one of the custom views is present when browsing the SIARD.
> 
> The created siardfile contains only one view, the latest we wrote and saved in the create phase:
> strings systemx.siard |grep -i CUSTOM_VIEW|sort -u
> CUSTOM_VIEW_Diarieplan
> 
> Any ideas why?

**Comment by martenlindstrandx** [comment]
Thanks for your support, I caught the yaml config file from the desktop client and ran dbptk-app-2.8.1.jar migrate --import = import-config --import-file = systemx.yaml ... Works fine!

**Comment by hmiguim** [comment]
Closed at 3d632dd
