### ISSUE TITLE
dbptk desktop -> configuration changes (comments of tables) do not affect browse -> Information page

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#217]
1. Changed some configuration of siard
![image](https://user-images.githubusercontent.com/3479156/81913741-0b679100-95d9-11ea-8193-900f077ed838.png)

2. Clicked "Save" and application told that everything was stored

3. Clicked Manage Database -> Browse
Under the Information there are still old comments:
![image](https://user-images.githubusercontent.com/3479156/81913931-4f5a9600-95d9-11ea-964e-d9cac44e9788.png)

4. But it shows updated comment on the page of "table"
![image](https://user-images.githubusercontent.com/3479156/81914173-9cd70300-95d9-11ea-9b84-211857d0a12c.png)

**Comment by hmiguim** [comment]
Close at 88423c2
