### ISSUE TITLE
search date field format error

### ISSUE THREAD

**Issue by Laurira** [keeps/db-visualization-toolkit#40]
Server gives error 500 when user tries to search some specific date (from_date for example). Maybe there should be a hint of which format to use and/or the error message should give the clue.

![dateformatissue](https://cloud.githubusercontent.com/assets/3479156/17508219/8c2dac00-5e1c-11e6-939c-066bcdddfd3f.jpg)

**Comment by chalkos** [comment]
The format to use is YYYY-MM-DDTHH:MM:SSZ, example: 1998-02-10T00:00:00Z

An enhancement to this is planned, using a date picker and allowing searching a date (and time) range. As it will also add more features, I created an issue for that (and I will close this one to avoid having the same functionality in two issues).

Please follow the development of this feature in #41
