### ISSUE TITLE
Missing visual clue that there are no results in "search whole database"

### ISSUE THREAD

**Issue by chalkos** [keeps/db-visualization-toolkit#46]
By @PhillipTommerholt:

> When I search in "search whole database" for something that does not exist in the database, I don't get a result that tells me that there were no results. So I was uncertain that it had actually searched until I tried with a term that did exist.

**Comment by chalkos** [comment]
There could also be another visual clue when the search is in progress.

**Comment by PhillipTommerholt** [comment]
> There could also be another visual clue when the search is in progress.

 :+1:
