### ISSUE TITLE
Consistent naming between the sidebar and the page itself

### ISSUE THREAD

**Issue by chalkos** [keeps/db-visualization-toolkit#48]
By @PhillipTommerholt:

> When you click "Data" you get "Table information".
> 
> ![image2](https://cloud.githubusercontent.com/assets/98429/17696667/c77f04d0-63a7-11e6-8148-98a4dc199244.png)
> 
> I think it is sad that this is hidden under "Data". Would it not be better if you had a "Table information"-tab right under the schema and then the "structure"-tab beneath it.?

**Comment by chalkos** [comment]
This was an effort to reduce the number of items in the sidebar.

> a "Table information" item right under the schema and then the "structure" item beneath it

@PhillipTommerholt like this?

```
• Schema <name>
  • Table Information
  • ... (routines, triggers, constraints, views, etc)
  • Structure
    • table A
    • table B
    • table C
    • ...
```

**Comment by PhillipTommerholt** [comment]
More like this
```
• Schema <name>
  • Table Information
  • Structure
  • ... (routines, triggers, constraints, views, etc)
    • table A
    • table B
    • table C
    • ...
```
In order to reduce the number of items in the sidebar I would suggest that routines, triggers, constraints, and views are merged into one category since these are for the more experienced users.

**Comment by chalkos** [comment]
> EDIT: But I don't have strongs feeling about the order - I just think "Table information" should be there.

The order was bothering me quite a bit, because the advancement hints at a page and sub-page hierarchy. And tables should be inside something like "data" or "structure" or "tables"...

> In order to reduce the number of items in the sidebar I would suggest that routines, triggers, constraints, and views are merged into one category since these are for the more experienced users.

We don't really have a problem with the sidebar length for now (maybe we will with databases containing multiple schemas with a couple hundred tables). If it becomes a problem we will have to find ways to reduce the number of items displayed, we'll handle it then.

**Comment by BorisDomajnko** [comment]
Sidebar lenght might be confusing for the archivists or users. On their first contact with the tool they may not be interested in technical info, but just in the queries.

**Comment by chalkos** [comment]
> Sidebar lenght might be confusing for the archivists or users. On their first contact with the tool they may not be interested in technical info, but just in the queries.

We will continue to try to find better ways to display sidebar information.
