### ISSUE TITLE
The proportions of the database listing at the front page is not user friendly

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-visualization-toolkit#50]
Reported by a colleage at the DNA:

The proportions of the database listing at the front page is not user friendly
![databaselisting](https://cloud.githubusercontent.com/assets/15984159/17772565/cf0d0dca-6549-11e6-8deb-5c6aa54d15f6.PNG)

**Comment by chalkos** [comment]
Does this happen on Internet Explorer?
Can you also tell me the browser version?

**Comment by PhillipTommerholt** [comment]
Yes.
Internet Explorer 11.
version 11.0.9600.18426CO.

**Comment by chalkos** [comment]
I believe this does not apply anymore, because this table now shows more information about the database.
