### ISSUE TITLE
Filter sidebar function is not easily noticed

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-visualization-toolkit#51]
Reported by a colleage at the DNA:

Filter sidebar function is not easily noticed
![filtererer](https://cloud.githubusercontent.com/assets/15984159/17772706/9d011ff0-654a-11e6-84e2-8049ebac3276.PNG)

**Comment by chalkos** [comment]
Does this happen on Internet Explorer?
Can you also tell me the browser version?

**Comment by PhillipTommerholt** [comment]
Yes.
 Internet Explorer 11.
 version 11.0.9600.18426CO.

**Comment by 006627** [comment]
Closed at 4187ff1, validated with BrowserStack
Internet Explorer 11.
version 11.175.18362.0
