### ISSUE TITLE
Footer - What is DB Viewer? 

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-visualization-toolkit#58]
In the footer there is a link About Database Viewer -  What is DB Viewer? 
But on the target page (http://www.database-preservation.com/) no "viewer" is mentioned.  However, Database Visualization Toolkit is mentioned at the beginning of the page. I suggest a section is added with some basic description of the DBVTK.

**Comment by chalkos** [comment]
Related to #30 
It will probably be added to that page and another page could be created with a detailed description.

**Comment by BorisDomajnko** [comment]
Maybe just change the link to: http://visualization.database-preservation.com/

**Comment by chalkos** [comment]
This has already been fixed. http://www.database-preservation.com/ includes basic DBVTK information and link to http://visualization.database-preservation.com/ (which is better to provide more insight about the tools and how they are used, not only about the DBVTK).
