### ISSUE TITLE
Support searching in views' contents

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-visualization-toolkit#59]
I can select a table and create a new search. But on the left I also see views. Are these the views available by the DBVTK or these just descriptions of original views taken form SIARD-2? I wanted to create a new search for a view as views and tables are displayed together in the left frame.

**Comment by chalkos** [comment]
*For now* views are just descriptive.

There were some discussions (internally) to save the contents of the views in SIARD as if they were tables, to be able to search them in a viewer. I will change the title of this issue to reflect this and this issue will be a feature request to save views in a way that their contents can be searchable in DBVTK

**Comment by luis100** [comment]
This issue is superseded by #145
