### ISSUE TITLE
When exporting to CSV we should put the column name on the header instead of col0_t

### ISSUE THREAD

**Issue by jmaferreira** [keeps/db-visualization-toolkit#65]
![screen shot 2016-09-27 at 22 36 02](https://cloud.githubusercontent.com/assets/3181302/18892775/c9c22c14-8502-11e6-88df-aced583ff932.png)

**Comment by chalkos** [comment]
@chalkos use RODA's IndexResource#csvResponse method

**Comment by hmiguim** [comment]
Close at f19c75c
