### ISSUE TITLE
Adding new database makes it impossible to list databases

### ISSUE THREAD

**Issue by chalkos** [keeps/db-visualization-toolkit#77]
Problem reported by József (@mezeijozsef)

Steps required to reproduce the bug:

1. I restarted the workstation
2. Used the link: http://visualization.database-preservation.com/
3. Started the service with start.bat
4. Opened 127.0.0.1:8080, saw the preloaded sakila database
5. In the process I used the dbptk-app.jar in the folder

Now, the case is:

1. To make sure "sakila" is a part of the html code I checked and here is a screenshot: **(4 results)** ![knpjlpadfpjnbncc](https://cloud.githubusercontent.com/assets/98429/20602206/2020ab34-b254-11e6-85e7-1bc9d93e0438.png)
2. Importing a SIARD 2.0 with dbptk-app.jar: `java -Dfile.encoding=UTF-8 -jar dbptk-app.jar -i siard-2 -if 1999-904.siard -e solr` - The import was successful - I attached the logs. (bferreira: logs show everything was converted without problems).
3. After refreshing, I can see there are 2 uploaded databases, but the list is empty. I searched for sakila, but it has disappeared. Also, the imported database's name or description cannot be found. **(No results)** 
![2](https://cloud.githubusercontent.com/assets/98429/20602266/6d6aed1e-b254-11e6-8658-d8cd45b3ee57.png)

There also seems to be some javascript related error:

![dbvtk2js](https://cloud.githubusercontent.com/assets/98429/20602307/967884fa-b254-11e6-93e8-b1fb473a3a4d.JPG)

bferreira: the log file from tomcat did not show any errors.

**Comment by chalkos** [comment]
@mezeijozsef, according to our skype chat you were going to create a smaller SIARD file without confidential information that could be used to replicate this problem.

Do you have news on this?

**Comment by mezeijozsef** [comment]
This problem (empty DBVTK) occurred because I wanted to ingest siard 2.0 files that were created with the older version of DBPTK.
When I used the latest version of DBPTK and the ingestion was successful.
