### ISSUE TITLE
Table information page: Row headers not displayed completely

### ISSUE THREAD

**Issue by BorisDomajnko** [keeps/db-visualization-toolkit#79]
Given my browser font size I see instead of
Table name	Number of rows	Number of columns	Description
this:
Table name	Number of ro	Number of colum	Description

I suggest this:
Table name	Rows	Columns	Description

Besides, the first column Table name is much wider than needed, compared to max column name in a given table.

**Comment by chalkos** [comment]
> Given my browser font size I see instead of
> Table name	Number of rows	Number of columns	Description
> this:
> Table name	Number of ro	Number of colum	Description
> 
> I suggest this:
> Table name	Rows	Columns	Description

That is not a durable fix. Someone will always have a smaller screen/font size and will not see the complete text. I added tooltips to cells, so when you let your mouse hover the cell it should show a tooltip.

If the tooltip is not showing, feel free to open an issue about that.

> Besides, the first column Table name is much wider than needed, compared to max column name in a given table.

I don't think this is a problem.
