### ISSUE TITLE
Embedded mode

### ISSUE THREAD

**Issue by hsilva-keep** [keeps/db-visualization-toolkit#85]
An embedded mode must be available. Basically it removes header & footer for making it easier to embed.

How will it be activated? Query param? HTTP Header? ... It must be easier to set when doing HTTP request.

**Comment by chalkos** [comment]
This is done via a GET query parameter: `branding=false`

**Comment by chalkos** [comment]
more information in the wiki: https://github.com/keeps/db-visualization-toolkit/wiki/Configuration#remove-branding-header-and-footer
