### ISSUE TITLE
When the database only contains 1 table, the graphic schema view panel does not show any bubbles

### ISSUE THREAD

**Issue by jmaferreira** [keeps/db-visualization-toolkit#91]

**Comment by chalkos** [comment]
@jmaferreira I can not reproduce this. The diagram correctly shows 1 circle corresponding to the existing table.

**Comment by chalkos** [comment]
I'm assuming that the graphic schema view panel is the diagram.

**Comment by jmaferreira** [comment]
yes.

**Comment by chalkos** [comment]
Please try to reproduce this and send me the problematic DB or let me see the problem happening, since 1 table is showing correctly on my end.
