### ISSUE TITLE
Row data and structure not being shown in some databases

### ISSUE THREAD

**Issue by chalkos** [keeps/db-visualization-toolkit#98]
This happens when the table doesn't have a primary key.

**Comment by jmaferreira** [comment]
Why is there an assumption that a table should have a primary key!?
Weird!

**Comment by chalkos** [comment]
In the relational model, tables have primary keys so that rows can be identified atomically, this is necessary to have an organized collection of *things*, instead of just a pile of *things*. Most DBMSs support tables without primary keys but that just seems to be a very common implementation decision.
